ALLOWED_COLUMNS = [
    "id",
    "title",
    "description",
    "type",
    "price",
    "rooms",
    "restroom",
    "area_m2",
    "location",
    "published_date",
]

FORBIDDEN_KEYWORDS = [
    "INSERT",
    "UPDATE",
    "DELETE",
    "DROP",
    "ALTER",
    "TRUNCATE",
    "CREATE",
]


def validate_sql(sql: str) -> str:
    """
    Validate SQL generated by LLM

    Return -> str
    """
    sql_upper = sql.upper()

    for keyword in FORBIDDEN_KEYWORDS:
        if keyword in sql_upper:
            raise ValueError(f"Forbidden SQL keyword: {keyword}")

    if not sql_upper.startswith("SELECT"):
        raise ValueError("Only SELECT queries are allowed")

    if "real_estates" not in sql:
        raise ValueError("Invalid table")

    return sql
